### ISSUE TITLE
Regression tutorial might need more scaffolding

### ISSUE THREAD

**Issue by dannycab** [learningmachineslab/tutorials#8]
The tasks in the tutorial are appropriate for linear regression, but seem to assume a lot on the part of the participants. For example, even the first tasks just asks to develop 3 visualizations of the data to explain how things co-vary. Participants might need more scaffolding throughout to achieve the goals.

**Comment by mnky9800n** [comment]
i guess i figured they would have a whole module on making graphs from the day before. i think my solutions demonstrate the upper end of the expectation. if someone made several scatter plots instead of the scatter matrix function, this wouldn't be incorrect. This would build on the end of the solutions from the data visualization module from the day before.

**Comment by mnky9800n** [comment]
i think it was fine
